from .nodes import NODE_CLASS_MAPPINGS as MAIN_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MAIN_NAME_MAPPINGS
from .morse_nodes import NODE_CLASS_MAPPINGS as MORSE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MORSE_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(MAIN_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MAIN_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MORSE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MORSE_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]